// File generated by FlutterFire CLI.
// flutterfire configure --project=excelerate-next-app

import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  DefaultFirebaseOptions._();

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for this platform.',
        );
    }
  }

  /// Set to true after flutterfire configure successfully ran.
  static const bool isConfigured = true;

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7cBhETo9WBDxocHq4HWzBcKsiMT2quVs',
    appId: '1:242287283617:web:cc5382e9bce08fd7f84fe0',
    messagingSenderId: '242287283617',
    projectId: 'excelerate-next-app',
    authDomain: 'excelerate-next-app.firebaseapp.com',
    storageBucket: 'excelerate-next-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDhnzkfQed5JRWSOpLoBgBcoa3_4Dl0mE',
    appId: '1:242287283617:android:f4501f29a10edfb4f84fe0',
    messagingSenderId: '242287283617',
    projectId: 'excelerate-next-app',
    storageBucket: 'excelerate-next-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTNJbTvk63SPJT9bQYs04ZJqAhDEduet8',
    appId: '1:242287283617:ios:b93f260c76bf75b7f84fe0',
    messagingSenderId: '242287283617',
    projectId: 'excelerate-next-app',
    storageBucket: 'excelerate-next-app.firebasestorage.app',
    iosBundleId: 'com.example.excelerateNextApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTNJbTvk63SPJT9bQYs04ZJqAhDEduet8',
    appId: '1:242287283617:ios:b93f260c76bf75b7f84fe0',
    messagingSenderId: '242287283617',
    projectId: 'excelerate-next-app',
    storageBucket: 'excelerate-next-app.firebasestorage.app',
    iosBundleId: 'com.example.excelerateNextApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7cBhETo9WBDxocHq4HWzBcKsiMT2quVs',
    appId: '1:242287283617:web:421ef6611a7743d9f84fe0',
    messagingSenderId: '242287283617',
    projectId: 'excelerate-next-app',
    authDomain: 'excelerate-next-app.firebaseapp.com',
    storageBucket: 'excelerate-next-app.firebasestorage.app',
  );
}
